biomejs/biome-vscode

- package.json
- pnpm-lock.yaml
- src/commands/index.ts
- src/downloader.ts
- src/main.ts
- src/statusBar.ts
This PR implements a downloader that prompts users to download the Biome CLI if none is found. It is meant to replace the current strategy of bundling the CLI with the extension with every release.
https://github.com/biomejs/biome-vscode/assets/649677/c7c1bf81-10a5-4cd6-bbdf-019d983a2d6a
1. `pnpm install`
2. `F5`
3. Create a new folder with a `biome.json` file inside
4. Open that folder
5. Click on the `biome.json` file
6. A notification stating that biome is not installed should appear. click download
7. When biome is installed, try formatting a file
8. Click on the biome status bar, downgrade the version, the version should change
The code is admittedly a bit spaghetti, but I think it will do fine for now. We'll have to overhaul the majority of the logic if we want to support testing …
> feat: implement downloader

- lefthook.yml
- package.json
- pnpm-lock.yaml
This PR sets up `lefthook` to run pre-commit scripts automatically.
This only runs `biome check` on staged files to ensure they are correctly formatted and linted.
Fixes #9
> chore: setup lefthook

- cliff.toml
- package.json
- pnpm-lock.yaml
This PR sets up git-cliff to generate the changelog from conventional commits.
> chore: setup git-cliff

- src/main.ts
This PR adds a short-circuit mechanism to abort the activation of a stable version when a nightly version is installed in parallel and active.
> feat: handle stable and nightly version installed together

- README.md
Description:
Change `Thhis` to `This` in [README.md](https://github.com/biomejs/biome-vscode/blob/main/README.md).
> Docs: Fix typo `Thhis` on README.md

- src/main.ts
This PR loosens the constraints of the document filter to allow linting and formatting in-memory files.
Related to https://github.com/biomejs/biome/pull/1413
---
Fixes https://github.com/biomejs/biome-vscode/issues/35
> feat: allow formatting and linting of in-memory files

- src/downloader.ts
This PR fixes an issue where nightly version would not be shown correctly in the version selector. The list would appear as if there were duplicate versions.
> fix: nightly versions in selector

- src/downloader.ts
- src/main.ts
- src/statusBar.ts
This PR addresses issues that could arise when hitting the GitHub API rate limit.
When hitting the rate limit, the extension will now continue instead of crashing.
Additionally, some logging has been added when this happens so we can better troubleshoot it in the future.
Closes https://github.com/biomejs/biome-vscode/issues/56
Supersedes https://github.com/biomejs/biome-vscode/pull/57
> fix: handle versions list fetch failures

- src/main.ts
This PR fixes an issue brought to our attention by @utrolig, where the extension sends error notifications to the user after showing the diff editor.
In the latest version, we slightly changed the document filter to allow formatting and linting of untitled files. In doing so, we've let unwanted schemes be passed to Biome, and in this case, it passes files with the git scheme, which Biome does not handle.
The solution here is to add additional document filters and explicitly list the schemes we support instead of leaving them unspecified.
> fix: filter out unhandled schemes

- src/main.ts
Closes https://github.com/biomejs/biome/issues/1601
> fix: only watch lock files in workspace root

- package.json
- src/main.ts
> chore: stop using `null` for settings

- src/main.ts
This PR fixes an issue where Biome cannot be found from a workspace folder's dependencies if it's not the first workspace in the list.
When opening a VS Code workspace with multiple folders, the extension would loop through the list of workspace folders to locate the biome binary in the workspace's dependencies.
Unfortunately, a logic error prevented the extension from looking past the first workspace folder, which meant that depending on the folders' order, the extension could not locate Biome correctly.
> fix: scan workspace folders until biome is found

- src/main.ts
This PR adds support for using Yarn's PnP linker when resolving the path of the `biome` binary to use.
> feat: add Yarn PnP support

- package.json
- src/main.ts
This PR introduces a new feature to allow searching for the biome binary in the PATH.
Here's where it comes in the current detection order.
1. Search in `DEBUG_SERVER_PATH`
2. Look in `biome.lspBin`
3. Look in project's dependencies
4. **Search in PATH**
5. Download global binary
Possible fix for #127
> feat: search for `biome` in PATH

- src/main.ts
This PR adds the `astro`, `vue`, and `svelte` languages to the document filters so that they can be passed to the Biome LSP.
The upcoming version of Biome introduces partial support for formatting frontmatter in Astro files and `script` blocks of Vue and Svelte components. This PR updates the list of document filters so that the Biome LSP takes these new file types into consideration.
Document filters that reference `vue`, `svelte`, or `astro` will only work if an extension designed to handle these files is installed.
I do not expect this to be an issue, because it's fairly safe to assume that users of Astro, Vue and Svelte already use their respective VS Code extensions, which register their language identifiers.
This PR closes #140
> feat: add `astro`, `vue`, and `svelte` support

- README.md
Update the `editor.codeActionsOnSave` values in README.md.
With the release of VS Code 1.85, the editor.codeActionsOnSave settings have been transitioned to use corresponding enum values (https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto ). Therefore, it's necessary to update these values in README.md to reflect the change accordingly.
> docs: update `editor.codeActionsOnSave` values in README.md

- src/main.ts
> fix: workspace-relative paths in `biome.lspBin`

- .github/workflows/lint-pr-title.yaml
This PR adds a workflow for linting pr titles. It uses [amannn/action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request), used by some repositories ([Electron](https://github.com/electron/electron) · [Vite](https://github.com/vitejs/vite) · [Excalidraw](https://github.com/excalidraw/excalidraw) · [Apache](https://github.com/apache/pulsar) · [Vercel](https://github.com/vercel/ncc) · [Microsoft](https://github.com/microsoft/SynapseML) · [Firebase](https://github.com/firebase/flutterfire) · [AWS](https://github.com/aws-ia/terraform-aws-eks-blueprints)).
This is definition of each part.
```
feat(ui): Add `Button` component
^    ^    ^
|    |    |__ Subject
|    |_______ Scope
|____________ Type
```
I only added some types.
- fix
- feat
- chore
- ci
- docs
- …
> ci: add a workflow for linting pr titles

- src/main.ts
- src/utils.ts
This PR fixes the musl libc detection, allowing the extension to select the correct biome binary from the project's dependencies.
This PR closes #223
> fix: musl libc detection

- package.json
- src/main.ts
The PR enables the extension for CSS files. 
I had a couple of issues, not sure if they are relevant:
- `bun` updated the lock file, not sure why. I didn't add it to the commit though 
- When debugging the extension using `F5`, the extension didn't trigger for the CSS files. Is it expected?
- lefthook triggered when committing, and if it failed 
```
┃  check ❯ 
sh: biome: command not found
```
This feature should be released after (together) with the release of v1.8.
N/A
This PR closes #<issue_number>
> feat: enable extension for CSS files

- src/downloader.ts
- src/main.ts
Refactor to remove `@ts-expect-error`
This PR closes #<issue_number>
> refactor: reduce `@ts-expect-error` and more type safe

- CONTRIBUTING.md
- README.md
- src/downloader.ts
- src/main.ts
- src/utils.ts
Linux will now always use -musl builds.
Linux will now always use -musl builds, which are statically built and have no external dependencies. This will make the extension more compatible across Linux systems. Additionally, I fixed a bug where the downloader would never use musl builds even when on a musl system. I also fixed a small typo.
This change will only take in effect whenever a biome binary is updated.
This PR closes #295
> feat: use statically linked builds on Linux

- src/extension.ts
- src/utils.ts
Debounce configuration change events so that we don't restart the extension at every keystroke.
This PR fixes #322
> debounce config changes

- pnpm-lock.yaml
- src/utils.ts
Restore graphql support
Restore graphql support.
By the way, `pre-commit` fails with `noConsole` not being correct. It probably runs an old version of Biome
N/A
> fix: restore graphql support

- package.json
`s/start/starts`
N/A
This PR closes #<issue_number>
> Fix typo in Require Config setting description

- src/config.ts
- src/session.ts
This PR changes the way we start the global session.
Until now, the session was always created if the window had open files that Biome could handle but did not belong to any Biome project. This included global settings files and untitled files.
Following this PR, we stop creating the global session if `biome.enabled` is set to `false` at the global/user level. We will, however, continue creating it if the extension is disabled at the workspace/workspace folder level.
This PR closes #375
> fix global session lifecycle

- src/constants.ts
- src/downloader.ts
platformSpecificPackageName: 
```
biome-win32-arm64
biome-win32-x64
```
biome name
```
biome-win32-arm64.exe
biome-win32-x64.exe
```
> fix: windows download error

- src/binary-finder.ts
Allow specifying relative paths in `biome.lsp.bin`.
This PR re-introduces support for specifying relative paths in `biome.lsp.bin`. The paths are relative to the project root. In case of single-root workspaces this means the root of the workspace, in monorepos, this means the root of the biome project folder.
This PR closes #420
> fix: support relative paths in `biome.lsp.bin`

- lefthook.yaml
- src/extension.ts
1. added `bun.lock' to the lockfile glob pattern
2. updated the argument for the biome check command in the lefthook.yaml
- `bun.lock` is the newly supported format for bun's lockfile
- the argument `--apply ` is deprecated
N/A
> feat: lockfile glob pattern and command arg

- package.json
- pnpm-lock.yaml
- src/constants.ts
This fix ensures that we do not attempt to download the `musl` variant of Biome when running inside WSL.
This PR closes #486
> fix: do not use `musl` flavor in WSL

- package.json
- pnpm-lock.yaml
- src/downloader.ts
> [2.x] fix: do not use `musl` flavor on WSL

- src/binary-finder.ts
When setting an explicit binary using `biome.lsp.bin`, it was ignored.
Using `Uri.file()` seems to not work reliably for turning paths into a `Uri`. `Uri.parse()` works.
> fix: `biome.lsp.bin` detection

- lefthook.yaml
- src/binary-finder.ts
- src/config.ts
- src/downloader.ts
- src/project.ts
- src/session.ts
- src/state.ts
- src/status-bar.ts
- src/utils.ts
- tsconfig.json
Enables TypeScript `strict` checks and performed a little bit of code cleanups.
As I was just debugging the VS Code extension, I noticed there were quite a few subtle type issues that made it hard to reason about what was going on.
I also ran into an issue with `ky`, that I was able to resolve by changing from a static import to a dynamic one. It puzzled me slightly because I didn't change anything in the lock file.
> chore: strict TS checks

- src/session.ts
The extension copies binaries to a temp location, but skips this for versions that have already been copied.
For dev versions (`0.0.0`) we shouldn't copy at all or rebuilds don't get picked up.
> chore: don't copy dev version

- src/constants.ts
Add snippets to supported language identifiers
VS Code snippets are just JSON files, which is supported by Biome.
This PR closes #555
> feat: add snippets to supported language identifiers

- src/binary-finder.ts
- src/project.ts
- src/utils.ts
This PR changes the usage of `Uri.parse` by `Uri.file` to fix an issue where paths where incorrectly parsed on Windows, which would result in the extension not creating projects.
This PR closes #546
> fix: path parsing on windows

- src/constants.ts
This PR adds support for the `html` language (Biome `>= 2`).
The html formatter still needs to be explicitly enabled in the Biome configuration.
```
"html": {
"formatter": {
"enabled": true
}
},
```
> feat: enable html language

- .changeset/good-nights-fry.md
- src/locator.ts
- src/utils.ts
Adds support for locating Biome in global `node_modules` folders.
Supported package managers:
- npm
- pnpm
- bun  
Closes #640
Closes #641
Closes #642
Closes #643
> feat: add support for locating biome in global `node_modules`

- package.json
Removes the unsupported `compact` trace mode.
This PR closes #665
> fix: remove unsupported `compact` trace mode

- .changeset/ripe-ads-jump.md
- src/extension.ts
This PR fixes an issue where we would start multiple global instances when opening VS Code while the last active text editor was the VS Code settings.json file.
n/a
> fix: only start one global instance

- src/utils.ts
This PR fixes the handling of absolute paths in the `biome.lsp.bin` setting.
On Windows, this could lead to broken paths.
Now we'll check the path to determine whether an absolute path or a relative path was provided. If the path is absolute, it's taken as-is and if it's relative we'll resolve it against the root of the workspace folder.
n/a
> fix: absolute path handling in `biome.lsp.bin`
